#theme = "slick"
icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
info_bg = "#ad29c4"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
unit = "GB"
show_percentage = true
interval = 20
warning = -10.0
alert = -9.0

[[block]]
block = "backlight"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"

#[[block]]
#block = "memory"
#format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
#format_swap = "{SUm}MB/{STm}MB({SUp}%)"
#display_type = "memory"
#icons = true
#clickable = true
#interval = 5
#warning_mem = 80
#warning_swap = 80
#critical_mem = 95
#critical_swap = 95

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
graph_up = false
interval = 2
use_bits = false

[[block]]
block = "sound"

[[block]]
block = "pacman"
interval = 10
format = "{count} updates available"
format_singular = "{count} update available"
format_up_to_date = "system up to date"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
