#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Start picom
compton &!

# Set numlock to be on 
numlockx &

# display arrangement
xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal


# set backgrounds
feh --bg-center ~/src/useful-scripts/arch-desktop/eboy_ny.png \
    --bg-center ~/src/useful-scripts/arch-desktop/eboy_tok.png

# set keyboard params
xset r rate 250 50

# start the emacs server. disown so that exiting x session doesn't kill emacs
emacs --daemon &!

# set a few nice touchpad settings
xinput set-prop "DELL09E2:00 04F3:30CB Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "DELL09E2:00 04F3:30CB Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DELL09E2:00 04F3:30CB Touchpad" "libinput Middle Emulation Enabled" 1
