#!/bin/bash

# First argument is whether to increase or decrease brightness
upOrDown=$1

backlightHelper=/usr/libexec/gsd-backlight-helper

# Find current brightness
currBrightness="$( cat /sys/class/backlight/intel_backlight/actual_brightness )"

if [ $upOrDown = "up" ]; then
	newBrightness="$(echo $currBrightness + 10000 | bc)"
elif [ $upOrDown = "down" ]; then
	newBrightness="$(echo $currBrightness - 10000 | bc)"
else
	exit 1
fi

# Send a system notification for brightness
notify-send -t 800 "Display backlight set to ${newBrightness}"

# Set brightness
# sudo /usr/libexec/gsd-backlight-helper /sys/class/backlight/intel_backlight/ $newBrightness
sudo $backlightHelper /sys/class/backlight/intel_backlight/ $newBrightness
