#!/bin/bash

# Find whether the touchpad is disabled at present
curr="$(synclient -l | grep "Touchpad")"

# Split the line up by spaces into a list
cur=( $curr )

# Extract touchpad status
tpstat=${cur[2]}

if [ $tpstat = "1" ]; then
	synclient TouchpadOff=0
	xinput set-prop $(xinput | grep Touchpad | cut -f2 | cut -d= -f2) "Device Enabled" 1
	notify-send -t 1000 "Touchpad enabled"
	echo "Touchpad enabled"
else
	xinput set-prop $(xinput | grep Touchpad | cut -f2 | cut -d= -f2) "Device Enabled" 0
	synclient TouchpadOff=1
	notify-send -t 1000 "Touchpad disabled"
	echo "Touchpad disabled"
fi

