#!/bin/bash

# This script installs the shell and terminal,
# then symlinks their configs to the appropriate locations

# Install terminator and zsh
sudo pacman -S --noconfirm terminator zsh fortune-mod


# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install powerline theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k

# Install syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting


# Symlink config files
rm /home/hamish/.zshrc
ln -s /home/hamish/src/useful-scripts/x360/.zshrc /home/hamish/.zshrc
ln -s /home/hamish/src/useful-scripts/x360/terminator /home/hamish/.config/terminator
ln -s /home/hamish/src/useful-scripts/x360/.p10k.zsh /home/hamish/.p10k.zsh
