#theme = "slick"
icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
info_bg = "#ad29c4"
separator = "" # seeing as the powerline glyph didn't work properly

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "nvidia_gpu"
label = "GTX 1050 Ti"
show_memory = true
show_clocks = true
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
graph_up = true
interval = 1
use_bits = false

[[block]]
block = "net"
device = "enp2s0"
ssid = false
ip = true
speed_up = false
graph_down = true
interval = 1
use_bits = false
hide_missing = true

[[block]]
block = "battery"
driver = "upower"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
