#!/bin/bash


# Script for auto installing most of the useful stuff in a new system, then setting up git

sudo pacman -Syu

# Config git
git config --global user.email "ham430@gmail.com"
git config --global user.name "hacmorgan"

# Set up libinput
sudo ln -s /home/hamish/src/useful-scripts/x360/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf

# Run setup scripts
bash /home/hamish/src/useful-scripts/x360/install-scripts/system-utils
bash /home/hamish/src/useful-scripts/x360/install-scripts/shell-terminal
bash /home/hamish/src/useful-scripts/x360/install-scripts/editors
bash /home/hamish/src/useful-scripts/x360/install-scripts/graphical

# Install packages
sudo pacman -S --noconfirm gimp firefox 


# Don't forget that chmod 777 will make the ext4 filesystem of the sd card writable
