#!/bin/bash

# Script for auto installing most of the useful stuff in a new system, then setting up git

# Perform an update
sudo pacman -Syu

# Config git
git config --global user.email "ham430@gmail.com"
git config --global user.name "hacmorgan"

# Run the config scripts in install-scripts
bash /home/hamish/src/useful-scripts/arch-desktop/install-scripts/system-utils
bash /home/hamish/src/useful-scripts/arch-desktop/install-scripts/shell-terminal
bash /home/hamish/src/useful-scripts/arch-desktop/install-scripts/editors
bash /home/hamish/src/useful-scripts/arch-desktop/install-scripts/graphical

# Install other packages
sudo pacman -S --noconfirm gimp
