theme = "slick"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "nvidia_gpu"
label = "1050 Ti"
show_memory = true
show_clocks = true
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
driver = "upower"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
graph_down = true
interval = 1
use_bits = false
hide_missing = true

[[block]]
block = "net"
device = "enp2s0"
ssid = false
ip = true
speed_up = false
graph_down = true
interval = 1
use_bits = false
hide_missing = true


[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
