#theme = "slick"
icons = "awesome5"

[theme]
name = "slick"

[theme.overrides]
info_bg = "#ad29c4"
separator = ""

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "net"
device = "wlp1s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
graph_up = true
interval = 1
use_bits = false

#[[block]]
#block = "pacman"
#interval = 10
#format = "{count} updates available"
#format_singular = "{count} update available"
#format_up_to_date = "system up to date"

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "cat /home/hamish/scratch/.battery_level"
interval = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
