This is the canonical reference point for *all* projects, past, present and future.

If the project is big enough that it has its own /notes/ files, this should just be a link to that file.

* System Administration & Utilities
** TODO name-value-args
** TODO proper locationing of configs & cmake install for utilities
This does hinge to a certain extent on the potential for different platforms to share a single master copy of a config, and differ by branching. If symlinks are to be broken, and utilities on PATH are to be moved, this should all happen at once.

With that said, there is also a chance git branches won't work perfectly for this, as they /seem/ to be slightly more specialised for maintaining a code base. For this reason, the git branching thing should be the first thing investigated here.

*** TODO Transition some configs to a branching system to test if suitable
This has been working great, currently leaving the master branch as the desktop config, and having separate branches for everything else.

*** TODO Copy cmake stuff from Bedrock in order to install utilities
    
* Programming Languages
** Rust
*** TODO Work through a rust tutorial
*** TODO Contribute to i3status-rust 
**** TODO Determine if the project is too advanced

** C
*** TODO Work through CK&R


* Building Stuff
** [[~/src/projects/pelicomputer/plan.org][Pelicomp Rebuild]]


* Embedded
** Contemporary
*** RTEMS Quick Start Guide
**** TODO Review email from Chris to determine if can proceed


* Other people's projects
** Tour Calculator


* Completed
None 


* Abandoned
None, yet.
