#!/bin/bash

# Script to install and configure text editors

# Install packages
sudo pacman -S --noconfirm vim neovim emacs

# Install evilmode and cyberpunk
git clone --depth 1 https://github.com/emacs-evil/evil ~/.emacs.d/evil
git clone https://github.com/n3mo/cyberpunk-theme.el ~/.emacs.d/cyberpunk
git clone https://code.orgmode.org/bzg/org-mode.git ~/.emacs.d/org

# Symlink configs
if [ -f /home/hamish/.vimrc ]; then rm ~/.vimrc; fi
mkdir -p ~/.config/nvim
ln -s /home/hamish/src/useful-scripts/arch-desktop/.emacs /home/hamish/.emacs
ln -s /home/hamish/src/useful-scripts/arch-desktop/.vimrc /home/hamish/.config/nvim/init.vim


