#!/bin/bash

# This script installs and configures all things graphical (i.e. i3 and polybar etc)

# Install packages
sudo pacman -S --noconfirm i3-gaps xorg-server xorg-xinit dmenu

# Install polybar
cd /tmp
git clone https://aur.archlinux.org/polybar.git
cd polybar
makepkg -si


# Symlink configs
ln -s /home/hamish/src/useful-scripts/arch-desktop/i3 /home/hamish/.config/i3
ln -s /home/hamish/src/useful-scripts/arch-desktop/polybar /home/hamish/.config/polybar


