#!/bin/bash

# This script installs the shell and terminal,
# then symlinks their configs to the appropriate locations

mkdir -p $ZSH_CUSTOM/themes
# Install powerline theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k

# Install syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting


# Symlink config files
if [ -f /home/hamish/.zshrc ]; then rm /home/hamish/.zshrc; fi
ln -s /home/hamish/src/useful-scripts/arch-desktop/.zshrc /home/hamish/.zshrc
ln -s /home/hamish/src/useful-scripts/arch-desktop/terminator /home/hamish/.config/terminator
ln -s /home/hamish/src/useful-scripts/arch-desktop/.p10k.zsh /home/hamish/.p10k.zsh
