#!/bin/bash


# Script for continuing the install process once oh-my-zsh has been set up


# find which computer we are using
hostname=$(cat /etc/hostname)
if [[ $hostname = rgboi ]]; then
	pc_folder=arch-desktop
elif [[ $hostname = thinking_abou_dis ]]; then
	pc_folder=x360
else
	echo This PC\'s hostname was not recognised, has it changed?
	exit 1
fi


function zsh_themes() {
    ln -s /home/hamish/src/useful-scripts/$pc_folder/.zshrc /home/hamish/.zshrc
    mkdir -p $ZSH_CUSTOM/themes
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
    ln -s /home/hamish/src/useful-scripts/$pc_folder/.p10k.zsh /home/hamish/.p10k.zsh
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    # meslo fonts for powerline
    cd ~/src
    git clone https://aur.archlinux.org/nerd-fonts-meslo.git
    cd nerd-fonts-meslo
    makepkg -si
}


function sakura() {
    sudo pacman -S sakura
    ln -s /home/hamish/src/useful-scripts/generic/dots/sakura /home/hamish/.config/
}


function emacs() {
    sudo pacman -S emacs
    mkdir /home/hamish/.emacs.d
    ln -s /home/hamish/src/useful-scripts/$pc_folder/.emacs /home/hamish/.emacs
    git clone --depth 1 https://github.com/emacs-evil/evil ~/.emacs.d/evil
    git clone https://github.com/n3mo/cyberpunk-theme.el ~/.emacs.d/cyberpunk
    git clone https://code.orgmode.org/bzg/org-mode.git ~/.emacs.d/org
}

function neovim() {
    sudo pacman -S nvim
    ln -s /home/hamish/src/useful-scripts/generic/dots/nvim /home/hamish/.config/
}


function i3() {
    # clone and install i3-gaps-rounded from the AUR
    cd ~/src
    git clone https://aur.archlinux.org/i3-gaps-rounded-git.git
    cd i3-gaps-rounded-git
    makepkg -si
    ln -s /home/hamish/src/useful-scripts/$pc_folder/i3 /home/hamish/.config/i3

    # clone and install i3status-rust
    cd ~/src
    git clone https://aur.archlinux.org/i3status-rust.git
    cd i3status-rust
    makepkg -si
}


function freeCAD()
{
	cd ~/src
	mkdir freecad
	cd freecad
	aur_packages=( coin soqt med python-pivy freecad )
	for package in $aur_packages; do
		git clone https://aur.archlinux.org/$package.git
		cd $package
		makepkg -si
		cd ..
	done
}

# prepeare for symlinking configs
if [ -f /home/hamish/.zshrc ]; then rm /home/hamish/.zshrc; fi
if [ -f /home/hamish/.vimrc ]; then rm ~/.vimrc; fi
mkdir -p ~/.config/nvim

# symlink configs
echo Symlinking config files...
ln -s /home/hamish/src/useful-scripts/$pc_folder/compton.conf /home/hamish/.config/picom.conf
ln -s /home/hamish/src/useful-scripts/$pc_folder/.xinitrc /home/hamish/.xinitrc
ln -s /home/hamish/src/useful-scripts/$pc_folder/.zprofile /home/hamish/.zprofile

# Enable system time synchronisation
sudo systemctl enable systemd-timesyncd.service
sudo systemctl start systemd-timesyncd.service

# Enable NetworkManager
sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager

################################
#    DEVICE SPECIFIC THINGS    #
################################
if [[ $pc_folder = x360 ]]; then
	# Handle lid closing with systemd
	sudo mv /etc/systemd/logind.conf /etc/systemd/logind.conf
	sudo ln -s /home/hamish/src/useful-scripts/x360/logind.conf /etc/systemd/logind.conf

	# Set up libinput
	sudo ln -s /home/hamish/src/useful-scripts/x360/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf
fi
