#!/bin/bash


# Script for continuing the install process once oh-my-zsh has been set up


# find which computer we are using
hostname=$(cat /etc/hostname)
if [[ $hostname = rgboi ]]; then
	pc_folder=arch-desktop
elif [[ $hostname = x360 ]]; then
	pc_folder=x360
else
	echo This PC\'s hostname was not recognised, has it changed?
	exit 1
fi


####################
#    zsh themes    #
####################
# Make zsh custom stuff folder
mkdir -p $ZSH_CUSTOM/themes
# Install powerline theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
# Install syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting


############
#    st    #
############
mkdir ~/src && cd ~/src
git clone https://github.com/hacmorgan/st.git
cd st
sudo make clean install


#######################
#    Emacs Plugins    #
#######################
git clone --depth 1 https://github.com/emacs-evil/evil ~/.emacs.d/evil
git clone https://github.com/n3mo/cyberpunk-theme.el ~/.emacs.d/cyberpunk
git clone https://code.orgmode.org/bzg/org-mode.git ~/.emacs.d/org


####################
#    i3-rounded    #
####################
cd ~/src
git clone https://aur.archlinux.org/i3-gaps-rounded-git.git
cd i3-gaps-rounded-git
makepkg -si


# prepeare for symlinking configs
if [ -f /home/hamish/.zshrc ]; then rm /home/hamish/.zshrc; fi
if [ -f /home/hamish/.vimrc ]; then rm ~/.vimrc; fi
mkdir -p ~/.config/nvim

# symlink configs
echo Symlinking config files...
ln -s /home/hamish/src/useful-scripts/$pc_folder/.zshrc /home/hamish/.zshrc
ln -s /home/hamish/src/useful-scripts/$pc_folder/.p10k.zsh /home/hamish/.p10k.zsh
ln -s /home/hamish/src/useful-scripts/$pc_folder/.emacs /home/hamish/.emacs
ln -s /home/hamish/src/useful-scripts/$pc_folder/.vimrc /home/hamish/.config/nvim/init.vim
ln -s /home/hamish/src/useful-scripts/$pc_folder/i3 /home/hamish/.config/i3
ln -s /home/hamish/src/useful-scripts/$pc_folder/compton.conf /home/hamish/.config/picom.conf
ln -s /home/hamish/src/useful-scripts/$pc_folder/.xinitrc /home/hamish/.xinitrc
ln -s /home/hamish/src/useful-scripts/$pc_folder/.zprofile /home/hamish/.zprofile

# Enable system time synchronisation
sudo systemctl enable systemd-timesyncd.service
sudo systemctl start systemd-timesyncd.service
