#!/bin/bash

## This script is intended to be used with keybindings

function settings-run ()
{
    function edit-configs-run ()
    {
        # local configs="zsh,i3,i3status,emacs,picom,sakura"
        local configs="zsh,dwm,emacs,picom,st,xinit"
        local selected_config=$(echo $configs | sed 's/,/\n/g' | dmenu)
        case "$selected_config" in
            "zsh")
                /home/hamish/src/useful-scripts/generic/em ~/.zshrc ;;
            "i3")
                /home/hamish/src/useful-scripts/generic/em ~/.config/i3/config ;;
            "i3status")
                /home/hamish/src/useful-scripts/generic/em ~/.config/i3/status.toml ;;
            "dwm")
                /home/hamish/src/useful-scripts/generic/em ~/src/foss/dwm/config.h ;;
            "emacs")
                /home/hamish/src/useful-scripts/generic/em ~/.emacs.d/config.org ;;
            "picom")
                /home/hamish/src/useful-scripts/generic/em ~/.config/picom.conf ;;
            "sakura")
                /home/hamish/src/useful-scripts/generic/em ~/.config/sakura/sakura.conf ;;
            "st")
                /home/hamish/src/useful-scripts/generic/em ~/src/foss/st/config.h ;;
            "xinit")
                /home/hamish/src/useful-scripts/generic/em ~/.xinitrc ;;
        esac
    }

    function screenshot-run()
    {
        local screenshot_types="select region,full screen,select region (delay),full screen (delay)"
        local selected_type=$(echo "$screenshot_types" | sed 's/,/\n/g' | dmenu)
        case "$selected_type" in
            "select region")
                scrot -s -e 'mv $f /tmp/' ;;
            "full screen")
                scrot -e 'mv $f /tmp/' ;;
        esac
    }

    function keyboard-multiplier-run()
    {
        function select-delay()
        {
            local delays="150ms,250ms,500ms"
            local selected_delay=$(echo $delays | sed 's/,/\n/g' | dmenu | sed 's/ms//g')
            local current_rate=$(xset -q | grep delay | cut -d: -f3 | cut -d ' ' -f3)
            xset r rate $selected_delay $current_rate
        }
        function select-rate()
        {
            local rates="25,50,100,200"
            local selected_rate=$(echo $rates | sed 's/,/\n/g' | dmenu)
            local current_delay=$(xset -q | grep delay | cut -d: -f2 | cut -d ' ' -f3)
            xset r rate $current_delay $selected_rate
        }
        
        local configurable_params="delay,rate"
        local selected_param=$(echo "$configurable_params" | sed 's/,/\n/g' | dmenu)
        case "$selected_param" in
            "delay")
                select-delay ;;
            "rate")
                select-rate ;;
        esac
    }

    function picom-run()
    {
        local picom_options="turn on,turn off"
        local selected_option=$(echo $picom_options | sed 's/,/\n/g' | dmenu)
        case "$selected_option" in
            "turn on")
                [ $(ps -aux | grep picom | wc -l) -le 1 ] && exec picom ;;
            "turn off")
                killall picom ;;
        esac
    }
       
    subsetting_options="edit configs,keyboard multiplier,screenshot,picom"
    subsetting="$( echo $subsetting_options | sed 's/,/\n/g' | dmenu )"
    case "$subsetting" in
        "edit configs")
            edit-configs-run ;;
        "keyboard multiplier")
            keyboard-multiplier-run ;;
        "screenshot")
            screenshot-run ;;
        "picom")
            picom-run ;;
    esac
    
}




##############
#    MAIN    #
##############
# case "$1" in
#     settings)
#         settings-run ;;
#     scrot)
#         scrot-run ;;
# esac

    
settings-run
