#!/bin/bash

# Script to automatically pull code from all git repos, and commit and push any changes

# find which computer we are using
hostname=$(cat /etc/hostname)
if [[ $hostname = rgboi ]]; then
	pc_folder=arch-desktop
elif [[ $hostname = thinking_abou_dis ]]; then
	pc_folder=x360
elif [[ $hostname = inspiron ]]; then
	pc_folder=work-laptop
else
	echo This PC\'s hostname was not recognised, has it changed?
	exit 1
fi

# get absolute path of repo file
repo_file=$(realpath $(dirname "$0")/../$pc_folder/git-repos.txt)

# allow the script to be used to add a new repo
if [ $1 = "--add" ]; then
    echo $(realpath $2) >> $repo_file
fi    

for f in $(cat $repo_file)
do
	echo
	echo Updating git repo: $f
	cd $f
	git status
	git pull --recurse-submodules=yes \
		&& if [[ $1 = "-a" ]]; then git add . ; fi \
		&& git commit -a -m "automatic update" \
		&& git push &
done

