#!/bin/bash

# This script installs the shell and terminal,
# then symlinks their configs to the appropriate locations

# Install terminator, zsh, and fonts
#sudo pacman -S --noconfirm terminator zsh fortune-mod ttf-font-awesome


# Install oh-my-zsh
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install powerline theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/themes/powerlevel10k

# Install syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Install meso fonts for powerline
#cd /tmp
#git clone https://aur.archlinux.org/nerd-fonts-meslo.git
#cd nerd-fonts-meslo
#makepkg -si

# Symlink config files
rm /home/hamish/.zshrc
ln -s /home/hamish/src/useful-scripts/work-laptop/.zshrc /home/hamish/.zshrc
#ln -s /home/hamish/src/useful-scripts/work-laptop/.p10k.zsh /home/hamish/.p10k.zsh
